---
title: "simulation"
author: "Lulu Zhang"
date: "10/31/2019"
output: html_document
---

```{r}
library(tidyverse)

set.seed(1)

```

```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

```{r}
sim_regression(n = 30)
```


## rerun using a for loop

```{r}
output = vector("list", 5000)

for (i in 1:5000) {
  output[[i]] = sim_regression(30)
}

sim_results = bind_rows(output) %>% 
  ggplot(aes(x = beta0_hat))+
  geom_density()
sim_results
```

rerun simulation using `purr`

```{r}
sim_results = 
  rerun(5000, sim_regression(30, 2, 3)) %>% 
  bind_rows()
```


```{r}
sim_results %>% 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) + 
  geom_point()
```

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

sim_data %>% 
  ggplot(aes(x = x, y = y))+ geom_point()+
  stat_smooth(method = "lm", se = FALSE)
```

```{r}
sim_results %>% 
  pivot_longer(
    beta0_hat:beta1_hat,
    names_to =  "parameter",
    values_to =   "estimate") %>% 
  group_by(parameter) %>% 
  summarize(emp_mean = mean(estimate),
            emp_var = var(estimate)) %>% 
  knitr::kable(digits = 3)
```

## try another sample size

```{r}
n_list = list("n_30"  = 30, 
              "n_60"  = 60, 
              "n_120" = 120, 
              "n_240" = 240)
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(1000, sim_regression(n_list[[i]])) %>% 
    bind_rows
}

output[[4]] %>% 
  ggplot(aes(x = beta0_hat))+
  geom_density()
```


```{r}
sim_results = 
  tibble(sample_size = c(30, 60, 120, 240)) %>% 
  mutate(
    output_list = map(.x = sample_size, ~rerun(1000, sim_regression(n = .x))),
    output_df = map(output_list, bind_rows))%>% 
  select(~output_list) %>% 
  unnest(output_df)
      
```

```{r}
simulate_n_regressions = function(n_runs = 100, n, beta0 = 2, beta1 = 3) {
  
  rerun(n_runs, sim_regression(n, beta0, beta1)) %>% 
    bind_rows()
  
}

sim_results = 
  tibble(sample_size = c(30, 60, 120, 240)) %>% 
  mutate(estimate_dfs = map(.x = sample_size, ~simulate_n_regressions(n = .x))) %>% 
  unnest
```

```{r}
sim_results = 
  tibble(sample_size = c(30, 60, 120, 240)) %>% 
  mutate(
    estimate_dfs = map(.x = sample_size, ~simulate_n_regressions(n_runs = 1000, n = .x))
  ) %>% 
  unnest
```













